const mongoose = require('mongoose');

const { Schema,model } = mongoose;

const detailsSchema = Schema({
    cases: Number,
    deaths: Number,
    recovered: Number
},{ _id : false });
const countryDataSchema = Schema({
    Country: String,
    TotalCases: String,
    NewCases: String,
    TotalDeaths: String,
    NewDeaths: String,
    TotalRecovered: String,
    ActiveCases: String,
    SeriousCritical: String,
    TotCasesPer1MPop: String
},{ _id : false });
const allCountrySchema = Schema({
    "China":countryDataSchema,
      "Italy":countryDataSchema,
      "Iran":countryDataSchema,
      "S. Korea":countryDataSchema,
      "Spain":countryDataSchema,
      "Germany":countryDataSchema,
      "France":countryDataSchema,
      "USA":countryDataSchema,
      "Switzerland":countryDataSchema,
      "Norway":countryDataSchema,
      "Netherlands":countryDataSchema,
      "Sweden":countryDataSchema,
      "UK":countryDataSchema,
      "Denmark":countryDataSchema,
      "Japan":countryDataSchema,
      "Diamond Princess":countryDataSchema,
      "Belgium":countryDataSchema,
      "Austria":countryDataSchema,
      "Qatar":countryDataSchema,
      "Bahrain":countryDataSchema,
      "Singapore":countryDataSchema,
      "Australia":countryDataSchema,
      "Canada":countryDataSchema,
      "Malaysia":countryDataSchema,
      "Finland":countryDataSchema,
      "Brazil":countryDataSchema,
      "Slovenia":countryDataSchema,
      "Hong Kong":countryDataSchema,
      "Israel":countryDataSchema,
      "Czechia":countryDataSchema,
      "Greece":countryDataSchema,
      "Iceland":countryDataSchema,
      "Portugal":countryDataSchema,
      "Kuwait":countryDataSchema,
      "UAE":countryDataSchema,
      "Iraq":countryDataSchema,
      "India":countryDataSchema,
      "San Marino":countryDataSchema,
      "Egypt":countryDataSchema,
      "Lebanon":countryDataSchema,
      "Thailand":countryDataSchema,
      "Romania":countryDataSchema,
      "Ireland":countryDataSchema,
      "Indonesia":countryDataSchema,
      "Poland":countryDataSchema,
      "Saudi Arabia":countryDataSchema,
      "Philippines":countryDataSchema,
      "Taiwan":countryDataSchema,
      "Russia":countryDataSchema,
      "Vietnam":countryDataSchema,
      "Estonia":countryDataSchema,
      "Brunei":countryDataSchema,
      "Palestine":countryDataSchema,
      "Albania":countryDataSchema,
      "Chile":countryDataSchema,
      "Argentina":countryDataSchema,
      "Croatia":countryDataSchema,
      "Serbia":countryDataSchema,
      "Slovakia":countryDataSchema,
      "Peru":countryDataSchema,
      "Panama":countryDataSchema,
      "Algeria":countryDataSchema,
      "Luxembourg":countryDataSchema,
      "Georgia":countryDataSchema,
      "South Africa":countryDataSchema,
      "Bulgaria":countryDataSchema,
      "Costa Rica":countryDataSchema,
      "Pakistan":countryDataSchema,
      "Belarus":countryDataSchema,
      "Ecuador":countryDataSchema,
      "Oman":countryDataSchema,
      "Hungary":countryDataSchema,
      "Latvia":countryDataSchema,
      "Azerbaijan":countryDataSchema,
      "North Macedonia":countryDataSchema,
      "Colombia":countryDataSchema,
      "Cyprus":countryDataSchema,
      "Tunisia":countryDataSchema,
      "Bosnia and Herzegovina":countryDataSchema,
      "Mexico":countryDataSchema,
      "Malta":countryDataSchema,
      "Macao":countryDataSchema,
      "Senegal":countryDataSchema,
      "Armenia":countryDataSchema,
      "Jamaica":countryDataSchema,
      "Maldives":countryDataSchema,
      "Morocco":countryDataSchema,
      "Afghanistan":countryDataSchema,
      "Lithuania":countryDataSchema,
      "French Guiana":countryDataSchema,
      "Moldova":countryDataSchema,
      "Paraguay":countryDataSchema,
      "Cambodia":countryDataSchema,
      "Dominican Republic":countryDataSchema,
      "New Zealand":countryDataSchema,
      "Sri Lanka":countryDataSchema,
      "Réunion":countryDataSchema,
      "Liechtenstein":countryDataSchema,
      "Ukraine":countryDataSchema,
      "Bangladesh":countryDataSchema,
      "Bolivia":countryDataSchema,
      "Channel Islands":countryDataSchema,
      "Cuba":countryDataSchema,
      "Faeroe Islands":countryDataSchema,
      "French Polynesia":countryDataSchema,
      "Martinique":countryDataSchema,
      "Monaco":countryDataSchema,
      "Nigeria":countryDataSchema,
      "Burkina Faso":countryDataSchema,
      "Cameroon":countryDataSchema,
      "DRC":countryDataSchema,
      "Ghana":countryDataSchema,
      "Honduras":countryDataSchema,
      "Kazakhstan":countryDataSchema,
      "Saint Martin":countryDataSchema,
      "Turkey":countryDataSchema,
      "Guyana":countryDataSchema,
      "Sudan":countryDataSchema,
      "Andorra":countryDataSchema,
      "Jordan":countryDataSchema,
      "Nepal":countryDataSchema,
      "Bhutan":countryDataSchema,
      "Cayman Islands":countryDataSchema,
      "Ivory Coast":countryDataSchema,
      "Ethiopia":countryDataSchema,
      "Gabon":countryDataSchema,
      "Gibraltar":countryDataSchema,
      "Guadeloupe":countryDataSchema,
      "Guinea":countryDataSchema,
      "Vatican City":countryDataSchema,
      "Kenya":countryDataSchema,
      "Mongolia":countryDataSchema,
      "St. Barth":countryDataSchema,
      "St. Vincent Grenadines":countryDataSchema,
      "Togo":countryDataSchema,
      "Trinidad and Tobago":countryDataSchema
},{_id:false});
const dataSchema = Schema({
    timestamp: String,
    date: String,
    time: String,
    details: detailsSchema,
    top_country: [countryDataSchema],
    all_country_data: allCountrySchema
});

module.exports=model('Data', dataSchema)